version: '3'

services:
  quickwit:
    image: quickwit/quickwit:latest
    container_name: quickwit
    ports:
      # - "16686:16686"
      # - "14268:14268"
      # - "14250:14250"
      # - "9411:9411"
      - "4317:4317"
      # - "4318:4318"
      # - "14269:14269"
      # - "6831:6831"
      # - "6832:6832"
      # - "5778:5778"
      - "7280:7280"
      - "7281:7281"
    environment:
      # - COLLECTOR_ZIPKIN_HOST_PORT=9411
      # - COLLECTOR_OTLP_ENABLED=true
      - QW_ENABLE_OTLP_ENDPOINT=true
    command: run