GET http://localhost:3086

###

GET http://localhost:3086/api/test

###

POST http://localhost:3086/echo
Content-Type: application/json

{
  "foo": "bar"
}

###

POST http://localhost:3086/save
Content-Type: application/json

{
  "foo": "bar"
}

###

POST http://localhost:3086/users
Content-Type: application/json

{
  "username": "Alice"
} 