GET http://localhost:3086

###

POST http://localhost:3086/api/categories
Content-Type: application/json

{
  "name": "Category 1"
}

###

GET http://localhost:3086/api/categories

###

GET http://localhost:3086/api/categories/7cw7w5kkguq7oozs7xfr

###

PUT http://localhost:3086/api/categories/7cw7w5kkguq7oozs7xfr
Content-Type: application/json

{
  "name": "Category 1 Updated"
}

###

PUT http://localhost:3086/api/categories/7cw7w5kkguq7oozs7xfr
Content-Type: application/json

{
  "age": 28
}

###

GET http://localhost:3086/api/test

###

POST http://localhost:3086/echo
Content-Type: application/json

{
  "foo": "bar"
}

###

POST http://localhost:3086/save
Content-Type: application/json

{
  "foo": "bar"
}

###

POST http://localhost:3086/users
Content-Type: application/json

{
  "username": "Alice"
} 